// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArB6WQSOJEXEaLgn9wOfeqVF3p1MNjxpA',
    appId: '1:522177580140:web:5def24a48785b425b39c49',
    messagingSenderId: '522177580140',
    projectId: 'petquest-f820c',
    authDomain: 'petquest-f820c.firebaseapp.com',
    storageBucket: 'petquest-f820c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyo45TOri0m7TcBvp-S0BPaaGJUc-E9XE',
    appId: '1:522177580140:android:e628898b7bbde42cb39c49',
    messagingSenderId: '522177580140',
    projectId: 'petquest-f820c',
    storageBucket: 'petquest-f820c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZu769jp4uvD7vhlhJrN5kNFQUyaLDlY',
    appId: '1:522177580140:ios:1ad84a68509829aeb39c49',
    messagingSenderId: '522177580140',
    projectId: 'petquest-f820c',
    storageBucket: 'petquest-f820c.firebasestorage.app',
    iosBundleId: 'com.example.petquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuZu769jp4uvD7vhlhJrN5kNFQUyaLDlY',
    appId: '1:522177580140:ios:1ad84a68509829aeb39c49',
    messagingSenderId: '522177580140',
    projectId: 'petquest-f820c',
    storageBucket: 'petquest-f820c.firebasestorage.app',
    iosBundleId: 'com.example.petquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArB6WQSOJEXEaLgn9wOfeqVF3p1MNjxpA',
    appId: '1:522177580140:web:c17af2d34f57d3ffb39c49',
    messagingSenderId: '522177580140',
    projectId: 'petquest-f820c',
    authDomain: 'petquest-f820c.firebaseapp.com',
    storageBucket: 'petquest-f820c.firebasestorage.app',
  );
}
